server:
  port: 8084

rest:
  connect-timeout-ms: 4000
  read-timeout-ms: 6000

spring:
  application:
    name: graphe-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

services:
  authBaseUrl: http://localhost:8087
  evaluationBaseUrl: http://localhost:8083
  activityBaseUrl: http://localhost:8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true